### ISSUE TITLE
story: ad support for private locations

### ISSUE THREAD

**Issue by pilimartinez** [checkly/terraform-provider-checkly#159]
### Allow provider to handle new Checkly Private Locations

- [ ] Add CRUD methods
- [ ] Allow private location assignments in check/groups
- [ ] Add the required tests
- [ ] Update docs and examples
